name: test

on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: Install stable toolchain
        uses: actions-rs/toolchain@main
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo build
        run: cargo build

      - name: cargo build
        run: cargo test --workspace
