name: test

on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: cache cargo
        id: cache-cargo
        uses: actions/cache@main
        with:
          path: |
            ~/.cargo
            ~/.rustup
            ${{ github.workspace }}/target
          key: ${{ runner.os }}-cargo

      - name: cargo test
        run: cargo test --workspace
