name: test

on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup-cargo-pre
        uses: ./.github/actions/setup-cargo-pre

      - name: cargo test
        run: cargo test --workspace

      - name: setup-cargo-post
        uses: ./.github/actions/setup-cargo-post
