name: cargo-release
on:
  workflow_call:
    inputs:
      execute:
        description: --execute
        type: boolean
        default: false

      publish:
        description: publish
        type: boolean
        default: true

      release_level:
        description: level to release
        type: string
        default: release

      dev_level:
        description: level to bump after release
        type: string
        default: alpha

      environment:
        description: GitHub Actions environment to run on
        type: string
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      CARGO_HOME: ${{ github.workspace }}/.cache/cargo
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}
      EXECUTE: "${{ inputs.execute && '--execute' || '' }}"

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup-job
        uses: ./.github/actions/setup-job
        with:
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}

      - name: release version
        if: ${{ inputs.release_level != 'none' }}
        run: |
          cargo release version --no-confirm ${{ inputs.release_level }} ${{ env.EXECUTE }}

      - name: release hook validation
        if: ${{ inputs.release_level != 'none' }}
        run: |
          cargo release hook --no-confirm --unpublished ${{ env.EXECUTE }}

      - name: release version tag and push
        if: ${{ inputs.release_level != 'none' && inputs.execute }}
        run: |
          cargo release commit --no-confirm ${{ env.EXECUTE }}
          cargo release tag --no-confirm ${{ env.EXECUTE }}
          cargo release push --no-confirm ${{ env.EXECUTE }}

      - name: publish
        if: ${{ inputs.publish }}
        run: |
          cargo release publish --no-confirm ${{ env.EXECUTE }}

      - name: bump version
        if: ${{ inputs.dev_level != 'none' }}
        run: |
          cargo release version --no-confirm ${{ inputs.dev_level }} ${{ env.EXECUTE }}

      - name: bump version tag and push
        if: ${{ inputs.dev_level != 'none' && inputs.execute }}
        run: |
          cargo release commit --no-confirm ${{ env.EXECUTE }}
          cargo release push --no-tag --no-confirm ${{ env.EXECUTE }}

      - name: setup-cargo-post
        uses: ./.github/actions/setup-cargo-post
        if: always()
