name: cargo-release
on:
  workflow_call:
    inputs:
      execute:
        description: --execute
        type: boolean
        default: false

      publish:
        description: publish
        type: boolean
        default: true

      release_level:
        description: level to release
        type: string
        default: release

      dev_level:
        description: level to bump after release
        type: string
        default: alpha

      environment:
        description: GitHub Actions environment to run on
        type: string
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    env:
      CARGO_HOME: ${{ github.workspace }}/.cache/cargo
      CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_TOKEN }}

      # some steps should be executed even in dry run mode so that their
      # outputs are accurate. e.g., if we do not execute the version bump,
      # but then do a dry run publish, the latter step only shows the previous
      # (current) version, not the new version. Most of these release steps can
      # be executed on the worker even in dry run mode, since the changes can
      # simply be discarded by not being pushed back to the git repo
      EXECUTE: ${{ inputs.execute && '--execute' || '' }}

      CARGO_RELEASE_ARGS: >-
        --config ${{ github.workspace }}/.release//${{ inputs.execute && 'execute.toml' || 'dryrun.toml' }}
        --no-confirm

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup-job
        uses: ./.github/actions/setup-job
        with:
          git_user_name: ${{ secrets.GIT_USER_NAME }}
          git_email: ${{ secrets.GIT_EMAIL }}

      - name: release version
        if: ${{ inputs.release_level != 'none' }}
        run: |
          cargo release version ${{ env.CARGO_RELEASE_ARGS }} ${{ inputs.release_level }} --execute

      - name: release hook validation
        if: ${{ inputs.release_level != 'none' }}
        run: |
          cargo release hook ${{ env.CARGO_RELEASE_ARGS }} --unpublished --execute

      - name: release version tag and push
        if: ${{ inputs.release_level != 'none' }}
        run: |
          cargo release commit ${{ env.CARGO_RELEASE_ARGS }} --execute
          cargo release tag ${{ env.CARGO_RELEASE_ARGS }} --execute
          cargo release push ${{ env.CARGO_RELEASE_ARGS }} ${{ env.EXECUTE }}

      - name: publish
        if: ${{ inputs.publish }}
        run: |
          cargo release publish ${{ env.CARGO_RELEASE_ARGS }} ${{ env.EXECUTE }}

      - name: bump version
        if: ${{ inputs.dev_level != 'none' }}
        run: |
          cargo release version ${{ env.CARGO_RELEASE_ARGS }} ${{ inputs.dev_level }} --execute

      - name: commit and push
        if: ${{ inputs.dev_level != 'none' }}
        run: |
          cargo release commit ${{ env.CARGO_RELEASE_ARGS }} --execute
          cargo release push ${{ env.CARGO_RELEASE_ARGS }} --no-tag ${{ env.EXECUTE }}

      - name: setup-cargo-post
        uses: ./.github/actions/setup-cargo-post
        if: always()
