name: release
on:
  workflow_dispatch:
    inputs:
      publish:
        description: publish
        type: boolean
        default: true

      release_level:
        description: level to release
        type: choice
        options:
          - none
          - major
          - minor
          - patch
          - release
          - rc
          - beta
          - alpha
        default: release

      dev_level:
        description: level to bump after release
        type: choice
        options:
          - none
          - rc
          - beta
          - alpha
        default: alpha

env:
  CARGO_HOME: ${{ github.workspace }}/.cache/cargo
  NU_LOG_LEVEL: info

jobs:
  release-dry-run:
    uses: ./.github/workflows/cargo-release.yml
    with:
      publish: ${{ inputs.publish }}
      release_level: ${{ inputs.release_level }}
      dev_level: ${{ inputs.dev_level }}
      execute: false
    secrets: inherit

  release-execute:
    needs:
      - release-dry-run
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/cargo-release.yml
    with:
      environment: approval
      publish: ${{ inputs.publish }}
      release_level: ${{ inputs.release_level }}
      dev_level: ${{ inputs.dev_level }}
      execute: true
    secrets: inherit
